blank_issues_enabled: false
contact_links:
  - name: New general issue
    url: https://github.com/net-daemon/netdaemon/issues/new
    about: This is the main issue tracker for NetDaemon. Please report issues with the NetDaemon there.
  - name: I have a question or need support
    url: https://discord.gg/K3xwfcX
    about: Joint the Discord server to get support from the community.
  - name: Add and discuss a feature request
    url: https://github.com/net-daemon/netdaemon/discussions
    about: Please join the github discussions and ask for a feature in the feature request channel
  - name: I'm unsure where to go
    url: https://discord.gg/K3xwfcX
    about: If you are unsure where to go, then joining our chat in Discord is recommended; Just ask!