name: Validate with HACS

on:
  push:
    branches:
      - main
  pull_request:
      branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v3

      - name: 👀 Validate
        uses: hacs/action@main
        with:
          category: "integration"
          ignore: brands wheels