name: Validate with hassfest

on:
  push:
    branches:
      - main
  pull_request:
      branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v3

      - name: 👀 Validate
        uses: home-assistant/actions/hassfest@master